// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: audio_core/v1/audio_core.proto

package audiocorepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AudioCore_DetectVoice_FullMethodName = "/audio_core.v1.AudioCore/DetectVoice"
	AudioCore_Health_FullMethodName      = "/audio_core.v1.AudioCore/Health"
)

// AudioCoreClient is the client API for AudioCore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AudioCoreClient interface {
	DetectVoice(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AudioChunk, VadResponse], error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type audioCoreClient struct {
	cc grpc.ClientConnInterface
}

func NewAudioCoreClient(cc grpc.ClientConnInterface) AudioCoreClient {
	return &audioCoreClient{cc}
}

func (c *audioCoreClient) DetectVoice(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AudioChunk, VadResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AudioCore_ServiceDesc.Streams[0], AudioCore_DetectVoice_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AudioChunk, VadResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AudioCore_DetectVoiceClient = grpc.BidiStreamingClient[AudioChunk, VadResponse]

func (c *audioCoreClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, AudioCore_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AudioCoreServer is the server API for AudioCore service.
// All implementations must embed UnimplementedAudioCoreServer
// for forward compatibility.
type AudioCoreServer interface {
	DetectVoice(grpc.BidiStreamingServer[AudioChunk, VadResponse]) error
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedAudioCoreServer()
}

// UnimplementedAudioCoreServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAudioCoreServer struct{}

func (UnimplementedAudioCoreServer) DetectVoice(grpc.BidiStreamingServer[AudioChunk, VadResponse]) error {
	return status.Error(codes.Unimplemented, "method DetectVoice not implemented")
}
func (UnimplementedAudioCoreServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedAudioCoreServer) mustEmbedUnimplementedAudioCoreServer() {}
func (UnimplementedAudioCoreServer) testEmbeddedByValue()                   {}

// UnsafeAudioCoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AudioCoreServer will
// result in compilation errors.
type UnsafeAudioCoreServer interface {
	mustEmbedUnimplementedAudioCoreServer()
}

func RegisterAudioCoreServer(s grpc.ServiceRegistrar, srv AudioCoreServer) {
	// If the following call panics, it indicates UnimplementedAudioCoreServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AudioCore_ServiceDesc, srv)
}

func _AudioCore_DetectVoice_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AudioCoreServer).DetectVoice(&grpc.GenericServerStream[AudioChunk, VadResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AudioCore_DetectVoiceServer = grpc.BidiStreamingServer[AudioChunk, VadResponse]

func _AudioCore_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AudioCoreServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AudioCore_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AudioCoreServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AudioCore_ServiceDesc is the grpc.ServiceDesc for AudioCore service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AudioCore_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "audio_core.v1.AudioCore",
	HandlerType: (*AudioCoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _AudioCore_Health_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DetectVoice",
			Handler:       _AudioCore_DetectVoice_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "audio_core/v1/audio_core.proto",
}
