// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: audio_core/v1/audio_core.proto

package audiocorepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SampleFormat int32

const (
	SampleFormat_SAMPLE_FORMAT_UNSPECIFIED SampleFormat = 0
	SampleFormat_SAMPLE_FORMAT_PCM_S16LE   SampleFormat = 1
)

// Enum value maps for SampleFormat.
var (
	SampleFormat_name = map[int32]string{
		0: "SAMPLE_FORMAT_UNSPECIFIED",
		1: "SAMPLE_FORMAT_PCM_S16LE",
	}
	SampleFormat_value = map[string]int32{
		"SAMPLE_FORMAT_UNSPECIFIED": 0,
		"SAMPLE_FORMAT_PCM_S16LE":   1,
	}
)

func (x SampleFormat) Enum() *SampleFormat {
	p := new(SampleFormat)
	*p = x
	return p
}

func (x SampleFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SampleFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_audio_core_v1_audio_core_proto_enumTypes[0].Descriptor()
}

func (SampleFormat) Type() protoreflect.EnumType {
	return &file_audio_core_v1_audio_core_proto_enumTypes[0]
}

func (x SampleFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SampleFormat.Descriptor instead.
func (SampleFormat) EnumDescriptor() ([]byte, []int) {
	return file_audio_core_v1_audio_core_proto_rawDescGZIP(), []int{0}
}

type VadState int32

const (
	VadState_VAD_STATE_UNSPECIFIED   VadState = 0
	VadState_VAD_STATE_SILENCE       VadState = 1
	VadState_VAD_STATE_SPEECH        VadState = 2
	VadState_VAD_STATE_MAYBE_SILENCE VadState = 3
)

// Enum value maps for VadState.
var (
	VadState_name = map[int32]string{
		0: "VAD_STATE_UNSPECIFIED",
		1: "VAD_STATE_SILENCE",
		2: "VAD_STATE_SPEECH",
		3: "VAD_STATE_MAYBE_SILENCE",
	}
	VadState_value = map[string]int32{
		"VAD_STATE_UNSPECIFIED":   0,
		"VAD_STATE_SILENCE":       1,
		"VAD_STATE_SPEECH":        2,
		"VAD_STATE_MAYBE_SILENCE": 3,
	}
)

func (x VadState) Enum() *VadState {
	p := new(VadState)
	*p = x
	return p
}

func (x VadState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VadState) Descriptor() protoreflect.EnumDescriptor {
	return file_audio_core_v1_audio_core_proto_enumTypes[1].Descriptor()
}

func (VadState) Type() protoreflect.EnumType {
	return &file_audio_core_v1_audio_core_proto_enumTypes[1]
}

func (x VadState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VadState.Descriptor instead.
func (VadState) EnumDescriptor() ([]byte, []int) {
	return file_audio_core_v1_audio_core_proto_rawDescGZIP(), []int{1}
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_audio_core_v1_audio_core_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audio_core_v1_audio_core_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_audio_core_v1_audio_core_proto_rawDescGZIP(), []int{0}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	VadBackend    string                 `protobuf:"bytes,2,opt,name=vad_backend,json=vadBackend,proto3" json:"vad_backend,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_audio_core_v1_audio_core_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_audio_core_v1_audio_core_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_audio_core_v1_audio_core_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetVadBackend() string {
	if x != nil {
		return x.VadBackend
	}
	return ""
}

type AudioChunk struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SequenceNumber uint64                 `protobuf:"varint,1,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	SampleRateHz   uint32                 `protobuf:"varint,2,opt,name=sample_rate_hz,json=sampleRateHz,proto3" json:"sample_rate_hz,omitempty"`
	Channels       uint32                 `protobuf:"varint,3,opt,name=channels,proto3" json:"channels,omitempty"`
	SampleFormat   SampleFormat           `protobuf:"varint,4,opt,name=sample_format,json=sampleFormat,proto3,enum=audio_core.v1.SampleFormat" json:"sample_format,omitempty"`
	DurationMs     uint32                 `protobuf:"varint,5,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Pcm            []byte                 `protobuf:"bytes,6,opt,name=pcm,proto3" json:"pcm,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AudioChunk) Reset() {
	*x = AudioChunk{}
	mi := &file_audio_core_v1_audio_core_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioChunk) ProtoMessage() {}

func (x *AudioChunk) ProtoReflect() protoreflect.Message {
	mi := &file_audio_core_v1_audio_core_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioChunk.ProtoReflect.Descriptor instead.
func (*AudioChunk) Descriptor() ([]byte, []int) {
	return file_audio_core_v1_audio_core_proto_rawDescGZIP(), []int{2}
}

func (x *AudioChunk) GetSequenceNumber() uint64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *AudioChunk) GetSampleRateHz() uint32 {
	if x != nil {
		return x.SampleRateHz
	}
	return 0
}

func (x *AudioChunk) GetChannels() uint32 {
	if x != nil {
		return x.Channels
	}
	return 0
}

func (x *AudioChunk) GetSampleFormat() SampleFormat {
	if x != nil {
		return x.SampleFormat
	}
	return SampleFormat_SAMPLE_FORMAT_UNSPECIFIED
}

func (x *AudioChunk) GetDurationMs() uint32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *AudioChunk) GetPcm() []byte {
	if x != nil {
		return x.Pcm
	}
	return nil
}

type VadDecision struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SpeechProbability float32                `protobuf:"fixed32,1,opt,name=speech_probability,json=speechProbability,proto3" json:"speech_probability,omitempty"`
	IsSpeech          bool                   `protobuf:"varint,2,opt,name=is_speech,json=isSpeech,proto3" json:"is_speech,omitempty"`
	State             VadState               `protobuf:"varint,3,opt,name=state,proto3,enum=audio_core.v1.VadState" json:"state,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *VadDecision) Reset() {
	*x = VadDecision{}
	mi := &file_audio_core_v1_audio_core_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VadDecision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VadDecision) ProtoMessage() {}

func (x *VadDecision) ProtoReflect() protoreflect.Message {
	mi := &file_audio_core_v1_audio_core_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VadDecision.ProtoReflect.Descriptor instead.
func (*VadDecision) Descriptor() ([]byte, []int) {
	return file_audio_core_v1_audio_core_proto_rawDescGZIP(), []int{3}
}

func (x *VadDecision) GetSpeechProbability() float32 {
	if x != nil {
		return x.SpeechProbability
	}
	return 0
}

func (x *VadDecision) GetIsSpeech() bool {
	if x != nil {
		return x.IsSpeech
	}
	return false
}

func (x *VadDecision) GetState() VadState {
	if x != nil {
		return x.State
	}
	return VadState_VAD_STATE_UNSPECIFIED
}

type VadResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SequenceNumber uint64                 `protobuf:"varint,1,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	Vad            *VadDecision           `protobuf:"bytes,2,opt,name=vad,proto3" json:"vad,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VadResponse) Reset() {
	*x = VadResponse{}
	mi := &file_audio_core_v1_audio_core_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VadResponse) ProtoMessage() {}

func (x *VadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_audio_core_v1_audio_core_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VadResponse.ProtoReflect.Descriptor instead.
func (*VadResponse) Descriptor() ([]byte, []int) {
	return file_audio_core_v1_audio_core_proto_rawDescGZIP(), []int{4}
}

func (x *VadResponse) GetSequenceNumber() uint64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *VadResponse) GetVad() *VadDecision {
	if x != nil {
		return x.Vad
	}
	return nil
}

var File_audio_core_v1_audio_core_proto protoreflect.FileDescriptor

const file_audio_core_v1_audio_core_proto_rawDesc = "" +
	"\n" +
	"\x1eaudio_core/v1/audio_core.proto\x12\raudio_core.v1\"\x0f\n" +
	"\rHealthRequest\"I\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1f\n" +
	"\vvad_backend\x18\x02 \x01(\tR\n" +
	"vadBackend\"\xec\x01\n" +
	"\n" +
	"AudioChunk\x12'\n" +
	"\x0fsequence_number\x18\x01 \x01(\x04R\x0esequenceNumber\x12$\n" +
	"\x0esample_rate_hz\x18\x02 \x01(\rR\fsampleRateHz\x12\x1a\n" +
	"\bchannels\x18\x03 \x01(\rR\bchannels\x12@\n" +
	"\rsample_format\x18\x04 \x01(\x0e2\x1b.audio_core.v1.SampleFormatR\fsampleFormat\x12\x1f\n" +
	"\vduration_ms\x18\x05 \x01(\rR\n" +
	"durationMs\x12\x10\n" +
	"\x03pcm\x18\x06 \x01(\fR\x03pcm\"\x88\x01\n" +
	"\vVadDecision\x12-\n" +
	"\x12speech_probability\x18\x01 \x01(\x02R\x11speechProbability\x12\x1b\n" +
	"\tis_speech\x18\x02 \x01(\bR\bisSpeech\x12-\n" +
	"\x05state\x18\x03 \x01(\x0e2\x17.audio_core.v1.VadStateR\x05state\"d\n" +
	"\vVadResponse\x12'\n" +
	"\x0fsequence_number\x18\x01 \x01(\x04R\x0esequenceNumber\x12,\n" +
	"\x03vad\x18\x02 \x01(\v2\x1a.audio_core.v1.VadDecisionR\x03vad*J\n" +
	"\fSampleFormat\x12\x1d\n" +
	"\x19SAMPLE_FORMAT_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17SAMPLE_FORMAT_PCM_S16LE\x10\x01*o\n" +
	"\bVadState\x12\x19\n" +
	"\x15VAD_STATE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11VAD_STATE_SILENCE\x10\x01\x12\x14\n" +
	"\x10VAD_STATE_SPEECH\x10\x02\x12\x1b\n" +
	"\x17VAD_STATE_MAYBE_SILENCE\x10\x032\x9c\x01\n" +
	"\tAudioCore\x12H\n" +
	"\vDetectVoice\x12\x19.audio_core.v1.AudioChunk\x1a\x1a.audio_core.v1.VadResponse(\x010\x01\x12E\n" +
	"\x06Health\x12\x1c.audio_core.v1.HealthRequest\x1a\x1d.audio_core.v1.HealthResponseB]Z[github.com/abend-arg/speakerfocus/services/orchestrator-go/internal/audiocorepb;audiocorepbb\x06proto3"

var (
	file_audio_core_v1_audio_core_proto_rawDescOnce sync.Once
	file_audio_core_v1_audio_core_proto_rawDescData []byte
)

func file_audio_core_v1_audio_core_proto_rawDescGZIP() []byte {
	file_audio_core_v1_audio_core_proto_rawDescOnce.Do(func() {
		file_audio_core_v1_audio_core_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_audio_core_v1_audio_core_proto_rawDesc), len(file_audio_core_v1_audio_core_proto_rawDesc)))
	})
	return file_audio_core_v1_audio_core_proto_rawDescData
}

var file_audio_core_v1_audio_core_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_audio_core_v1_audio_core_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_audio_core_v1_audio_core_proto_goTypes = []any{
	(SampleFormat)(0),      // 0: audio_core.v1.SampleFormat
	(VadState)(0),          // 1: audio_core.v1.VadState
	(*HealthRequest)(nil),  // 2: audio_core.v1.HealthRequest
	(*HealthResponse)(nil), // 3: audio_core.v1.HealthResponse
	(*AudioChunk)(nil),     // 4: audio_core.v1.AudioChunk
	(*VadDecision)(nil),    // 5: audio_core.v1.VadDecision
	(*VadResponse)(nil),    // 6: audio_core.v1.VadResponse
}
var file_audio_core_v1_audio_core_proto_depIdxs = []int32{
	0, // 0: audio_core.v1.AudioChunk.sample_format:type_name -> audio_core.v1.SampleFormat
	1, // 1: audio_core.v1.VadDecision.state:type_name -> audio_core.v1.VadState
	5, // 2: audio_core.v1.VadResponse.vad:type_name -> audio_core.v1.VadDecision
	4, // 3: audio_core.v1.AudioCore.DetectVoice:input_type -> audio_core.v1.AudioChunk
	2, // 4: audio_core.v1.AudioCore.Health:input_type -> audio_core.v1.HealthRequest
	6, // 5: audio_core.v1.AudioCore.DetectVoice:output_type -> audio_core.v1.VadResponse
	3, // 6: audio_core.v1.AudioCore.Health:output_type -> audio_core.v1.HealthResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_audio_core_v1_audio_core_proto_init() }
func file_audio_core_v1_audio_core_proto_init() {
	if File_audio_core_v1_audio_core_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_audio_core_v1_audio_core_proto_rawDesc), len(file_audio_core_v1_audio_core_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_audio_core_v1_audio_core_proto_goTypes,
		DependencyIndexes: file_audio_core_v1_audio_core_proto_depIdxs,
		EnumInfos:         file_audio_core_v1_audio_core_proto_enumTypes,
		MessageInfos:      file_audio_core_v1_audio_core_proto_msgTypes,
	}.Build()
	File_audio_core_v1_audio_core_proto = out.File
	file_audio_core_v1_audio_core_proto_goTypes = nil
	file_audio_core_v1_audio_core_proto_depIdxs = nil
}
