# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from audio_core.v1 import audio_core_pb2 as audio__core_dot_v1_dot_audio__core__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in audio_core/v1/audio_core_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AudioCoreStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DetectVoice = channel.stream_stream(
                '/audio_core.v1.AudioCore/DetectVoice',
                request_serializer=audio__core_dot_v1_dot_audio__core__pb2.AudioChunk.SerializeToString,
                response_deserializer=audio__core_dot_v1_dot_audio__core__pb2.VadResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/audio_core.v1.AudioCore/Health',
                request_serializer=audio__core_dot_v1_dot_audio__core__pb2.HealthRequest.SerializeToString,
                response_deserializer=audio__core_dot_v1_dot_audio__core__pb2.HealthResponse.FromString,
                _registered_method=True)


class AudioCoreServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DetectVoice(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AudioCoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DetectVoice': grpc.stream_stream_rpc_method_handler(
                    servicer.DetectVoice,
                    request_deserializer=audio__core_dot_v1_dot_audio__core__pb2.AudioChunk.FromString,
                    response_serializer=audio__core_dot_v1_dot_audio__core__pb2.VadResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=audio__core_dot_v1_dot_audio__core__pb2.HealthRequest.FromString,
                    response_serializer=audio__core_dot_v1_dot_audio__core__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'audio_core.v1.AudioCore', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('audio_core.v1.AudioCore', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AudioCore(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DetectVoice(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/audio_core.v1.AudioCore/DetectVoice',
            audio__core_dot_v1_dot_audio__core__pb2.AudioChunk.SerializeToString,
            audio__core_dot_v1_dot_audio__core__pb2.VadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/audio_core.v1.AudioCore/Health',
            audio__core_dot_v1_dot_audio__core__pb2.HealthRequest.SerializeToString,
            audio__core_dot_v1_dot_audio__core__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
