# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: audio_core/v1/audio_core.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'audio_core/v1/audio_core.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x61udio_core/v1/audio_core.proto\x12\raudio_core.v1\"\x0f\n\rHealthRequest\"5\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x13\n\x0bvad_backend\x18\x02 \x01(\t\"\xa5\x01\n\nAudioChunk\x12\x17\n\x0fsequence_number\x18\x01 \x01(\x04\x12\x16\n\x0esample_rate_hz\x18\x02 \x01(\r\x12\x10\n\x08\x63hannels\x18\x03 \x01(\r\x12\x32\n\rsample_format\x18\x04 \x01(\x0e\x32\x1b.audio_core.v1.SampleFormat\x12\x13\n\x0b\x64uration_ms\x18\x05 \x01(\r\x12\x0b\n\x03pcm\x18\x06 \x01(\x0c\"d\n\x0bVadDecision\x12\x1a\n\x12speech_probability\x18\x01 \x01(\x02\x12\x11\n\tis_speech\x18\x02 \x01(\x08\x12&\n\x05state\x18\x03 \x01(\x0e\x32\x17.audio_core.v1.VadState\"O\n\x0bVadResponse\x12\x17\n\x0fsequence_number\x18\x01 \x01(\x04\x12\'\n\x03vad\x18\x02 \x01(\x0b\x32\x1a.audio_core.v1.VadDecision*J\n\x0cSampleFormat\x12\x1d\n\x19SAMPLE_FORMAT_UNSPECIFIED\x10\x00\x12\x1b\n\x17SAMPLE_FORMAT_PCM_S16LE\x10\x01*o\n\x08VadState\x12\x19\n\x15VAD_STATE_UNSPECIFIED\x10\x00\x12\x15\n\x11VAD_STATE_SILENCE\x10\x01\x12\x14\n\x10VAD_STATE_SPEECH\x10\x02\x12\x1b\n\x17VAD_STATE_MAYBE_SILENCE\x10\x03\x32\x9c\x01\n\tAudioCore\x12H\n\x0b\x44\x65tectVoice\x12\x19.audio_core.v1.AudioChunk\x1a\x1a.audio_core.v1.VadResponse(\x01\x30\x01\x12\x45\n\x06Health\x12\x1c.audio_core.v1.HealthRequest\x1a\x1d.audio_core.v1.HealthResponseB]Z[github.com/abend-arg/speakerfocus/services/orchestrator-go/internal/audiocorepb;audiocorepbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'audio_core.v1.audio_core_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z[github.com/abend-arg/speakerfocus/services/orchestrator-go/internal/audiocorepb;audiocorepb'
  _globals['_SAMPLEFORMAT']._serialized_start=472
  _globals['_SAMPLEFORMAT']._serialized_end=546
  _globals['_VADSTATE']._serialized_start=548
  _globals['_VADSTATE']._serialized_end=659
  _globals['_HEALTHREQUEST']._serialized_start=49
  _globals['_HEALTHREQUEST']._serialized_end=64
  _globals['_HEALTHRESPONSE']._serialized_start=66
  _globals['_HEALTHRESPONSE']._serialized_end=119
  _globals['_AUDIOCHUNK']._serialized_start=122
  _globals['_AUDIOCHUNK']._serialized_end=287
  _globals['_VADDECISION']._serialized_start=289
  _globals['_VADDECISION']._serialized_end=389
  _globals['_VADRESPONSE']._serialized_start=391
  _globals['_VADRESPONSE']._serialized_end=470
  _globals['_AUDIOCORE']._serialized_start=662
  _globals['_AUDIOCORE']._serialized_end=818
# @@protoc_insertion_point(module_scope)
